name: Update versions from tag

on:
  push:
    tags:
      - '*.*.*'

jobs:
  update-build-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Setup verion env vars
        run: |
          if [ "${{ steps.get_version.outputs.is-semver }}" = "true" ];then
            if [ "${{ steps.get_version.outputs.prerelease }}" = "" ];then
              RTYPE="release"
            else
              RTYPE="unstable"
            fi
            VER=${{ steps.get_version.outputs.version-without-v }}
          fi
          BLDDATE=$(date +'%Y-%m-%d')
          echo "rtype=${RTYPE}" >> $GITHUB_ENV
          echo "ver=${VER}" >> $GITHUB_ENV
          echo "OpenKJ Songbook Agent Version: $VER"
        shell: bash

      - name: Update Windows installer config files
        run: |
          sed -i "s/#define MyAppVersion.*/#define MyAppVersion \"${{ steps.get_version.outputs.version-without-v }}\"/" windows/openkj-songbook-agent_x86.iss
          sed -i "s/#define MyAppVersion.*/#define MyAppVersion \"${{ steps.get_version.outputs.version-without-v }}\"/" windows/openkj-songbook-agent_x86_64.iss

      - name: Update version.h
        run: |
          echo "Updating okjversion.h"
          echo "#ifndef VERSION_H" > src/version.h
          echo "#define VERSION_H" >> src/version.h
          echo >> src/version.h
          echo "#define VERSION_MAJOR ${{ steps.get_version.outputs.major }}" >> src/version.h
          echo "#define VERSION_MINOR ${{ steps.get_version.outputs.minor }}" >> src/version.h
          echo "#define VERSION_BUILD ${{ steps.get_version.outputs.patch }}" >> src/version.h
          echo "#define VERSION_STRING \"${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }}.${{ steps.get_version.outputs.patch }}\"" >> src/version.h
          echo "#define VERSION_BRANCH \"${{ env.rtype }}\"" >> src/okjversion.h
          echo >> src/version.h
          echo "#endif //VERSION_H" >> src/version.h

      - name: Commit changes to repo
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            src/version.h
            windows/openkj-songbook-agent_x86.iss
            windows/openkj-songbook-agent_x86_64.iss
          commit-msg: Auto commit - update version from git tag
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.branch }}
